<h1>Categorias</h1>
<br />

<ul>
    <?php foreach ($this->categorias as $categoria): ?>
         <li><?php echo $categoria; ?>
         
             <ul>   
               <?php foreach ($categoria->getinstrumentos() as $instrumento): ?>
                 <li><?php echo $instrumento->getNome(); ?></li>
               <?php endforeach; ?>                      
             </ul>
         </li>
    <?php endforeach; ?>
</ul>
