<h3>Novo Instrumento</h3>

<br />

<?php
$form = $this->form; 

$form->setAttribute('action', $this->url('loja-admin',array('controller'=>'instrumentos','action'=>'new')));

$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('nome'));
echo $this->formRow($form->get('categoria'));
echo $this->formRow($form->get('valor'));
echo $this->formRow($form->get('marca'));

echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
