
<h1>Categorias</h1>
<br />

<p> 
    <a href="<?php echo  $this->url('loja-admin',array('controller'=>'categorias','action'=>'new')); ?>">Novo     </a>
</p>
<fieldset class="dois">
<table class="table">
    <tr>
        <th>ID</th>
        <th>Nome</th>
        <th>Ação</th>
    </tr>
    
    <?php foreach($this->data as $entity): ?>
    <tr>
        <td><?php echo $entity->getId(); ?></td>
        <td><?php echo $entity->getNome(); ?></td>
        <td>
            <a href="<?php echo $this->url('loja-admin-interna',
                  array('controller'=>'categorias','action'=>'edit','id'=>$entity->getID())); ?>">Editar</a>
            <a href="<?php echo $this->url('loja-admin-interna',
                  array('controller'=>'categorias','action'=>'delete','id'=>$entity->getID())); ?>">Deletar</a>
        </td>
   </tr>
    
    <?php endforeach; ?>
        
</table>
</fieldset>
<br />

<?php echo $this->paginationControl($this->data,'Sliding', 'paginator'); ?>
