<h3>Editando Músico</h3>

<br />

<?php
$form = $this->form; 

$form->setAttribute('action', $this->url('loja-admin-interna',array('controller'=>'musicos','action'=>'edit')));

$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('nome'));
echo $this->formRow($form->get('categoria'));
echo $this->formRow($form->get('cpf'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>